#' Generate a ggplot2 object from random walk coordinates.
#'
#' @param walk a walk as generated by \code{generate_walk()}
#' @param pattern a background pattern with x, y and color column
#' @param plot_colors colors for the plot
#'
#' @return a ggplot2 object.
#' @export
plot_random_walk = function(walk, pattern, plot_colors) {
  # init plot
  plot = ggplot2::ggplot() +
    ggplot2::coord_fixed() + ggplot2::theme_void()
  # Add pattern
  plot = plot + ggplot2::geom_point(
    data = pattern,
    mapping = ggplot2::aes(x,y, color = color),
    size = 0.2, stroke = 0)
  plot = plot + ggplot2::scale_color_identity()
  for (level in sort(unique(walk$level))) {
    for(depth in rev(sort(unique(walk$depth)))) {
      plot_data = walk[walk$level == level & walk$depth == depth, ]
      mapping = ggplot2::aes(x = x, y = y, group = group)
      plot = plot + ggplot2::geom_polygon(
        data = plot_data,
        mapping = mapping,
        alpha = 0.8,
        fill = sample(plot_colors, 1)
        )
    }
  }
  return(plot)
}
