#' Get a data frame of directions.
#'
#' @return a data frame with directions.
#' @export
get_directions = function() {
  directions = data.frame(
    direction = c("N", "E", "S", "W"),
    dx = c(0, 1, 0, -1),
    dy = c(1, 0, -1, 0)
    )
  return(directions)
}

#' Generate random steps into four wind directions.
#'
#' @param steps number of steps in the walk.
#'
#' @return a character vector.
#' @export
generate_steps = function(steps) {
  directions = get_directions()
  steps = directions[sample(nrow(directions), size = steps, replace = TRUE), ]
  return(steps)
}

#' Convert a random walk to coordinates.
#'
#' @param random_walk a data frame as generated by \code{generate_steps()}.
#'
#' @return a data frame of points.
#' @export
random_walk_coords = function(random_walk) {
  coords = data.frame(
    x = c(0, cumsum(random_walk$dx)),
    y = c(0, cumsum(random_walk$dy))
  )
  return(coords)
}

#' Generate a ggplot2 object from random walk coordinates.
#'
#' @param coords a data frame of points.
#'
#' @return a ggplot2 object.
#' @export
plot_random_walk_from_coords = function(coords) {
  plot = ggplot2::ggplot(data = coords,
                         ggplot2::aes(x = x, y = y)) +
    ggplot2::geom_path() +
    ggplot2::coord_fixed() +
    ggplot2::theme_void()
  return(plot)
}

#' Generate a random walk and return it as a ggplot2 object.
#'
#' @param steps number of steps in the walk.
#'
#' @return a ggplot2 object.
#' @export
generate_random_walk = function(steps) {
  steps = generate_steps(steps = steps)
  coords = random_walk_coords(steps)
  plot = plot_random_walk_from_coords(coords)
  return(plot)
}
